### ISSUE TITLE
获取$styleWrap的高度为什么直接在运行的时候获取

### ISSUE THREAD

**Issue by whutyzy** [qianlongo/resume-native#4]
后面动态添加style的时候，不是改变了$styleWrap的高度吗？为什么不需要重新获取，而仍然按照第一次取的数字0计算，希望大佬能解答一下

**Comment by qianlongo** [comment]
@whutyzy 

styles-wrap的高度是在styles.js里面定义好的`height: 90vh`

不好意思，能贴一下你有疑问的代码吗？

**Comment by whutyzy** [comment]
`const MAX_HEIGHT = $stylesWrap.height()`获取高度是在styleEditor文件里面获取的，然后直接赋值给了MAX_HEIGHT,接着再到`setInterval`不停的调用这个高度
```
if (currentStyle.length === length) {
        clearInterval(timer)
        resolve()
      } else {
        let top = $stylePre.height() - MAX_HEIGHT
        if (top > 0) {
          goBottom(top)
        }
        $style.html(currentStyle)
        $stylePre.html(Prism.highlight(currentStyle, Prism.languages.css))
```
但是`styleWrap`的高度最开始是没有定义的，样式是随着定时器的不停运行而在不停的动态改变，运行到`height:90vh`的时候高度才定下来。所以不是很理解为什么获取高度这条语句为什么不放在定时器里面

**Comment by qianlongo** [comment]
谢谢指出。MAX_HEIGHT永远为0，goBottom函数本意是出现滚动条之后才执行。但是这里很多处比较多的计算次数。已经在master分支改过来了，谢谢。

**Comment by whutyzy** [comment]
作为一个初学者，从你的代码中学习到了很多，比如抽象，命名，promise，谢谢你的代码分享
